name: experiment

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare data folder (optional)
        run: |
          mkdir -p data
          # Si tu veux mettre tes .xlsx dans data/, fais-le localement puis commit; sinon evaluate.py utilisera l'URL fallback.

      - name: Run evaluation
        run: |
          python evaluate.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts_models
          path: artifacts_models/
          if-no-files-found: warn
